version: '2'
services:
  db:
    build: ./kurofune-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    env_file:
      - .env
volumes:
  db_data:
    driver: local
