version: '2'
services:
  db:
    image: postgres:9.3
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
     - "5432:5432"
    env_file:
      - .env
volumes:
  db_data:
    driver: local
